### ISSUE TITLE
How to read secret file after it's declared

### ISSUE THREAD

**Issue by thornycrackers** [Mic92/sops-nix#147]
I might be fundamentally misunderstanding how to use this tool so please bear with. I have worked through the examples, I'm using a flake based setup and in my `configuration.nix` have set `sops.secrets.mysecret = {};` and can see that at `/run/secrets/mysecret` exists with the correct value. Later in my configuration, I'm trying to read the contents of the secret file with `builtins.readFile "${config.sops.secrets.mysecret.path}"` but I get the error `access to path /run/secrets/myexample is forbidden in restricted mode`. I'm trying to read the file because I want to use it's contents in some string interpolation but maybe that's not the correct usage of sops-nix? I also tried `neededForUsers` with the same result. Is sops-nix limited to just passing the value of secret paths into path options/configs strings rather than decrypting exposing the secrets during build time?

**Comment by Mic92** [comment]
You cannot read secrets with nix because this is at evaluation time. If you need this you need to keep those files unencrypted but than its world-readable to any user on the system. You can only read them at runtime on the system you deploy the secrets to from `/run/secrets/`. If you want to interpolate secrets into configuration files you can use `sed` or `envsubst` in the `preStart` phase of your service: https://github.com/NixOS/nixpkgs/blob/0699530f08290f34c532beedd66046825d9756fa/nixos/modules/services/monitoring/telegraf.nix#L69

**Comment by Mic92** [comment]
You can checkout the module https://github.com/Mic92/sops-nix/blob/0e0dcc74bae23c7ef7fb6251c43c277b827e8c34/modules/sops/default.nix#L297
It shows that secrets are only decrypted in the activation phase, which is part of `switch-to-configuration`
