### ISSUE TITLE
nix-darwin support

### ISSUE THREAD

**Issue by 4825764518** [Mic92/sops-nix#163]
Tangentially related to #62, it would be useful to be able to ship secrets on nix-darwin systems.

**Comment by SuperSandro2000** [comment]
Mic is probably happy to accept PRs. 😄 

PS `launchctl` is horrible to work with and debug stuff.

**Comment by Mic92** [comment]
Yes. patches are welcome. I don't actively use macOS and hence won't implement that myself.

**Comment by TrueLecter** [comment]
Hey guys!

I was browsing forks and noticed that @4825764518 actually made some decent progress regarding darwin implementation in their branch https://github.com/4825764518/sops-nix/tree/darwin. Maybe some of the maintainers could check it out?

**Comment by mlyxshi** [comment]
Add a minimal [launchd service](https://github.com/mlyxshi/sops-nix-darwin) based on https://github.com/4825764518/sops-nix/tree/darwin.

**Comment by pogobanane** [comment]
#268 implements darwin support for home-manager. 

Room for improvement:
- Adjusting for global darwin modules should be as easy as creating the nix files and documentation. 
- Also the docs could describe sops-nix behaviour on darwin better and darwin instructions need to be merged into the install guide

**Comment by panda2134** [comment]
This issue should not be closed. `nix-darwin` is still not supported, as #268 only allows using user-level secrets with `home-manager`, which is less safe than limiting access to root only.

**Comment by j-baker** [comment]
A note - I'm using sops-nix on an AWS Mac2.metal node. Here, the present home-manager support is insufficient because it is installed as a launchagent - it runs only when a user is logged in. I've found as a workaround that each time I update, I copy ~/Library/LaunchAgents/org.nix-community.sops-nix.plist (or whatever it is) to /Library/LaunchDaemons and then load it as root. It then works great.

**Comment by pcasaretto** [comment]
Hi there! My journey trough the nix world brought me here.
I was super happy that I managed to simplify secret management for my NixOS VM and equally stumped when I tried to move that to my macOS machine.
One of my short term goals is to learn more nix and contribute back to the community, and this feels like an interesting challenge to tackle.

@pogobanane what do you mean by "We'd need nixos tests though to proceed with that since the manual test matrix is getting too big otherwise"

**Comment by zimbatm** [comment]
New issue for nix-darwin support: https://github.com/Mic92/sops-nix/issues/409
