### ISSUE TITLE
Can we avoid two nixos rebuild ?

### ISSUE THREAD

**Issue by Et7f3** [Mic92/sops-nix#310]
From what I see

> Get a public key for your target machine

It need a ssh keys. So to install a nixos server we need to first install with default template and ssh.enable so we have an ssh key.

convert this ssh key to gpg to encrypt data.

Then rebuild again with sops enabled.

**Comment by colemickens** [comment]
While it still requires a rebuild after adding the new host key, I just deploy the same (minus the new sops encrypted data) configuration both times. Just pointing out you don't have to necessarily use a default template.

You could also provision an age key up-front, and then deploy that to the host, but that has its own trade-offs -- now that key exists in more places than just the target server.

Otherwise it feels like a bit of a chicken/egg unavoidable situation.

**Comment by Mic92** [comment]
I think is unavoidable to have the key provisioned first before running nixos-rebuild.
What we do with our nixos-anywhere deployments is uploading the key during installation, using the --extra-files parameter: https://github.com/numtide/nixos-anywhere
