### ISSUE TITLE
Error with DynamicUsers sevice config 

### ISSUE THREAD

**Issue by megheaiulian** [Mic92/sops-nix#424]
Sops errors during boot with 

```
/nix/store/909bd2m8bxl57s2xiqyrxq08yasnbk1v-sops-install-secrets-0.0.1/bin/sops-install-secrets: Manifest is not valid: Failed to lookup group 'kea': group: unknown group kea
```
It doesn't decrypt any other secrets  thou those are ok.
If run after that service it no longer complains.

**Comment by Mic92** [comment]
Yeah. I don't see a way to fix DynamicUser in sops-nix. I actually no longer see this issue since we got nsncd enabled in NixOS by default. It usually has something to do with nss not resolving the uid correctly. DynamicUser uids are provided by nss-systemd and we have a nsncd daemon running that might be restarted and temporary not resolving requests. My recommendation is to use either LoadCredential or disable DynamicUser (i don't see many advantages of using it to be honest since allocation of uids is easy enough).

**Comment by megheaiulian** [comment]
Not being able to work with DynamicUser make sense but they way this failed is quite unfriendly. 
Initially the deploy worked because when the activation script ran the user/group existed. Then on restart it failed. Additionally (and this is the worst actually) because that one secret failed all other secrets failed.

**Comment by Mic92** [comment]
The later point we should maybe improve. I also don't know if it make sense to retry user lookups (I currently don't know if they are failing because one service has been stopped or because it's temporary not available).
