### ISSUE TITLE
Not restarting home-manager service when rebuilding

### ISSUE THREAD

**Issue by arthsmn** [Mic92/sops-nix#463]
I have home-manager as a nixos module and noticed that when I rebuild I have to manually restart the sops-nix service, I would like to request that you make the home-manager module do this by itself.

**Comment by Mic92** [comment]
Does home-manager restart services these days? I am only aware of it proposing services to be restarted.

**Comment by w4tsn** [comment]
It seems that home-manager can restart services based on a diff - so if something changed in the file. If one needs to use something like systemd.user.services.restartTriggers in home-manager it can be done via `X-SwitchMethod` in the `[Unit]` section.

See related home-manager issue / question: https://github.com/nix-community/home-manager/issues/3865

Since sops-nix has a home-manager module which uses systemd user services it would be more consistent to also handle a restart of the service.

**Comment by w4tsn** [comment]
See duplicate issue #478 with a longer discussion and a work-around using config in `home.nix`.
