### ISSUE TITLE
Can not add new machines with respective secrets.yml

### ISSUE THREAD

**Issue by madonius** [Mic92/sops-nix#96]
I did setup sops for two machines whose file's I can access and edit with `sops machine1/secret.yml`
Today I added to further machines, and for some peculiar reason if I run
`sops laptop1/secret.yml` or `nix-shell -p sops --run "sops laptop1/secret.yml"`
I keep getting `config file not found and no keys provided through command line options`

The machine's public keys have been exported and the proposed `shell.nix` is present.

Any ideas?

**Comment by madonius** [comment]
With extensive help from @Ma27 I managed to figure it out. The issue is that with
```console
nix-shell -p sops
```
the `shell.nix` is being ignored. Thus the `SOPS_PGP_FP` stays empty

Hence, I think it's a bug in the documentation
https://github.com/Mic92/sops-nix/blame/master/README.md#L238

**Comment by Mic92** [comment]
I actually want to deprecate this hook and suggest to using `.sops.yaml`, which does not rely on magic environment variables:

https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml

**Comment by madonius** [comment]
That would be a good idea, the documentation should reflect that though. I don't have much of a clue where I would start ^^'

**Comment by antifuchs** [comment]
I undertook this migration today, and it results in a pretty pleasant experience. Here's the high points:

* Put a .sops.yaml file in my flake root directory, and reference all the paths to the secrets YAML files in my flake via path_regexp.
* Use a yaml reference scheme that's similar to @Mic92's (unfortunately, you can't interpolate existing lists, which makes it very unwieldy to carry "backup" keys on the entries)
* Then you can use `sops updatekeys path/to/secrets.yaml` to re-encrypt the secrets contained in that .yaml file with all the keys that the file should use.

There's just one annoyance that I believe `sopsGPGHook` takes care of (and that I couldn't replicate in this setup): You have to import all the .asc files from `keys/users` and `keys/hosts` into your gpg keyring, otherwise sops can't find the key to encrypt to.

**Comment by Mic92** [comment]
> I undertook this migration today, and it results in a pretty pleasant experience. Here's the high points:
> 
>     * Put a .sops.yaml file in my flake root directory, and reference all the paths to the secrets YAML files in my flake via path_regexp.
> 
>     * Use a yaml reference scheme that's similar to @Mic92's (unfortunately, you can't interpolate existing lists, which makes it very unwieldy to carry "backup" keys on the entries)
> 
>     * Then you can use `sops updatekeys path/to/secrets.yaml` to re-encrypt the secrets contained in that .yaml file with all the keys that the file should use.
> 
> 
> There's just one annoyance that I believe `sopsGPGHook` takes care of (and that I couldn't replicate in this setup): You have to import all the .asc files from `keys/users` and `keys/hosts` into your gpg keyring, otherwise sops can't find the key to encrypt to.

Yes. Maybe I just add an import hook that does not set environment variables.

**Comment by antifuchs** [comment]
> Yes. Maybe I just add an import hook that does not set environment variables.

Agreed! One thing that might work in addition is to set the `SOPS_GPG_EXEC` environment variable to a script that imports all keys/**/*.asc files into a temporary keyring - that could help ensure that the sops encryption operations are nice and hermetic, and help people keep the public keys checked in properly.

**Comment by Mic92** [comment]
sopsGgpHook is deprecated now: https://github.com/Mic92/sops-nix/pull/99

**Comment by antifuchs** [comment]
Thanks so much, I updated my flake config like so:

```nix
          apps = {
              edit-secrets = flake-utils.lib.mkApp {
                drv = pkgs.writeShellScriptBin "edit-secret" ''
                  nix develop -c sops "$1"
                '';
              };

              rekey-secrets = flake-utils.lib.mkApp {
                drv = pkgs.writeShellScriptBin "rekey-secret" ''
                  nix develop -c sops updatekeys "$1"
                '';
              };
            };

            devShell = pkgs.mkShell {
              sopsPGPKeyDirs = [
                "./keys/hosts"
                "./keys/users"
              ];
              sopsCreateGPGHome = true; # Make a keyring in .git/gnupg
              nativeBuildInputs = [
                (pkgs.callPackage sops-nix { }).sops-import-keys-hook
              ];
            };
```

And all that worked perfectly. In order to get my smartcard/yubikey-based secret keygrip imported, I had to run `gpg --card-status` inside the dev shell, but that was all. 

This is so much better than manually managing those keys, thank you so much!
